services:
  meeting-app-db:
    image: mysql:5.6
    restart: "on-failure"
    container_name: "meeting-app-db"
    env_file:
      - env.list
  meeting-app-be:
    image: javalog/meeting-app
    restart: "on-failure"
    container_name: "meeting-app-be"
    ports:
      - "9090:9090"
      - "59090:59090"
    env_file:
      - env.list
    depends_on:
      - meeting-app-db
version: "3.5"
